[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fast-face-python"
version = "0.1.1"
description = "Fast and easy face detection using ONNX runtime."
authors = [
  { name="xMaulana" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "Pillow",
    "opencv-python",
    "pydantic-settings>=2.15.0",
    "tqdm>=4.70.1",
]

[project.optional-dependencies]
cpu = [
    "onnxruntime>=1.24.3",
]
gpu = [
    "onnxruntime-gpu>=1.24.3, <=1.26.1",
    "nvidia-cudnn-cu12",
    "nvidia-cublas-cu12",
    "nvidia-cuda-runtime-cu12"
]
openvino = [
    "onnxruntime-openvino>=1.24.1"
]
rocm = [
    "onnxruntime-rocm>=1.22.1"
]
dev = [
    "pytest",
    "ruff",
    "build",
    "twine"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["fast_face", "fast_face.models"]

[tool.uv]
cache-dir = ".uv_cache"
